echo 正在安装依赖...
apt install git
echo 正在下载资源...
git clone https://gitee.com/SunWuKong443/acme-pack-installer/
echo 正在安装资源...
cd acme-pack-installer
sh ./install.sh
echo 正在清理己下载的资源...
cd ..
rm -rf acme-pack-installer
echo 安装成功！